### ISSUE TITLE
De url waarden van de server beschrijving bovenin de specificatie niet correct

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/Regels-bij-activiteiten#39]
De url waarden van de server beschrijving bovenin de specificatie (zie hieronder) komt niet overeen met de naam van de API.

```
servers:
  - description: "SwaggerHub API Auto Mocking"
    url: https://virtserver.swaggerhub.com/VNGRealisatie/api/plan_sw___toepasbare_regel_sw/v0
  - description: "Referentie-implementatie"
    url: https://www.voorbeeldgemeente.nl/api/plan_sw___toepasbare_regel_sw/v0

```
